### ISSUE TITLE
Can not Locate Bindings File

### ISSUE THREAD

**Issue by stuarthenrywilson** [paolotremadio/homebridge-automation-calendar#1]
Hi, 

Great work on the plugin! It's exactly what I was looking for.

I'm having an issue when I try to run the plugin, though. The following error is given in the log: 
`May 07 07:18:00 HomeHub homebridge[15614]: [2018-5-7 07:18:00] ERROR LOADING PLUGIN homebridge-automation-calendar:
May 07 07:18:00 HomeHub homebridge[15614]: [2018-5-7 07:18:00] Error: Could not locate the bindings file. Tried:
May 07 07:18:00 HomeHub homebridge[15614]:  → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/build/ed25519.node
May 07 07:18:00 HomeHub homebridge[15614]:  → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/build/Debug/ed25519.node
May 07 07:18:00 HomeHub homebridge[15614]:  → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/build/Release/ed25519.node
May 07 07:18:00 HomeHub homebridge[15614]:  → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/out/Debug/ed25519.node
May 07 07:18:00 HomeHub homebridge[15614]:  → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/Debug/ed25519.node
May 07 07:18:00 HomeHub homebridge[15614]:  → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/out/Release/ed25519.node
May 07 07:18:00 HomeHub homebridge[15614]:  → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/Release/ed25519.node
May 07 07:18:00 HomeHub homebridge[15614]:  → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/build/default/ed25519.node
May 07 07:18:00 HomeHub homebridge[15614]:  → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/compiled/10.0.0/linux/arm/ed25519.node
May 07 07:18:00 HomeHub homebridge[15614]:     at bindings (/usr/lib/node_modules/homebridge-automation-calendar/node_modules/bindings/bindings.js:93:9)
May 07 07:18:00 HomeHub homebridge[15614]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/index.js:1:99)
May 07 07:18:00 HomeHub homebridge[15614]:     at Module._compile (internal/modules/cjs/loader.js:678:30)
May 07 07:18:00 HomeHub homebridge[15614]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
May 07 07:18:00 HomeHub homebridge[15614]:     at Module.load (internal/modules/cjs/loader.js:589:32)
May 07 07:18:00 HomeHub homebridge[15614]:     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
May 07 07:18:00 HomeHub homebridge[15614]:     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
May 07 07:18:00 HomeHub homebridge[15614]:     at Module.require (internal/modules/cjs/loader.js:626:17)
May 07 07:18:00 HomeHub homebridge[15614]:     at require (internal/modules/cjs/helpers.js:20:18)
May 07 07:18:00 HomeHub homebridge[15614]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-automation-calendar/node_modules/hap-nodejs/lib/HAPServer.js:8:15)`

I've tried investigating the exact issue but I'm a little out of my depth. Do you have any ideas on how to solve this?

You might have noticed that I've changed the hostname of my pi—could that be causing the issue?

Thanks!

**Comment by paolotremadio** [comment]
Which version of node and homebridge are you running?
