### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by maschbaer** [paolotremadio/homebridge-automation-calendar#13]
Initiating an update for the automation calendar via Cinfig UI X end immediately with:
`USER: homebridge
DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-automation-calendar@latest

npm ERR! Unexpected end of JSON input while parsing near '...xdXQwIlDqPk9rgS4U5h24'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-07-16T20_52_21_533Z-debug.log

Command failed. Please review log for details.`

My current automation calendar version is "homebridge-automation-calendar v0.0.2"
My Homebridge runs as follows:

Node.js Version v12.16.3
Npm Version v6.14.4

see you
Jan

**Comment by paolotremadio** [comment]
I can't reproduce. Have you tried on another device?

**Comment by maschbaer** [comment]
What do you mean by other device? Installation/update of other plugins works.
Unfortunately I have Only one Homebridge device.

**Comment by paolotremadio** [comment]
Are you trying to install from the UI or from console?

**Comment by maschbaer** [comment]
Only via UI. I will try it via console on the weekend

**Comment by maschbaer** [comment]
No via console it does not work either...
`sudo npm i homebridge-automation-calendar
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ homebridge-automation-calendar@0.1.1
added 5 packages from 10 contributors and audited 218 packages in 10.729s

30 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~ $ sudo npm audit fix
npm ERR! code EAUDITNOPJSON
npm ERR! audit No package.json found: Cannot audit a project without a package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-21T20_26_14_544Z-debug.log
pi@raspberrypi:~ $ 
`

Beforehand I did a 
`sudo npm install -g npm@latest`
npm outdated

Any idea?

**Comment by paolotremadio** [comment]
Install the package using ‘-g’

**Comment by maschbaer** [comment]
Thanks it worked!
