### ISSUE TITLE
Winter time not recognized

### ISSUE THREAD

**Issue by ursusHU** [paolotremadio/homebridge-automation-calendar#15]
Currently the plugin still thinks it is autumn.
![DC7FF710-361C-433D-954E-31AE4F75CB56](https://user-images.githubusercontent.com/61931127/101469946-a7763280-3945-11eb-937d-bde080c43d57.png)

**Comment by paolotremadio** [comment]
First day of winter is Monday, December 21: https://www.almanac.com/content/first-day-seasons
If you don't like that definition, you can use a range in your automations based on `Month of the year` 😉

**Comment by ursusHU** [comment]
Sorry my bad :) I had in mind november 21
