### ISSUE TITLE
Summer / Wintertime

### ISSUE THREAD

**Issue by Nastras** [paolotremadio/homebridge-automation-calendar#2]
Hello, is it possible that you have for countries like Germany the one summer and winter time to incorporate this value with the automatically adjusts?

As an example 0 winter and 1 summer time.

Many Thanks

**Comment by paolotremadio** [comment]
Not sure if it is very easy to add since DST (Daylight saving time) does switch in different countries on different days. How would you use it in an automation?

**Comment by Nastras** [comment]
Thank you for your prompt reply!

I would need this value as a condition for my window cover each a trigger for the winter time and summertime. In winter, the normal sunset and sunrise should be triggered. And in the summer already X hours earlier because it is quite a long time bright by the time adjustment.

Since I do not always want to enable and disable the triggers as well as change them, this new value in your plugin would be very helpful.

Would not it be possible to set the country for the time calculation in the config to expand it internationally gradually when the need is there?

**Comment by paolotremadio** [comment]
Wait, I'm missing something 😊 The time on your Homekit will already change accordingly the summer time. I have a similar setting: I change the colour of the lights at 10pm to help me falling asleep. But 10pm is ok during the winter but a bit too early during the summer. So I have two automations, one for spring and summer, one for winter and autumn. Attached the examples. Would that work for you?

![image](https://user-images.githubusercontent.com/843553/41256718-559145fa-6dc2-11e8-93a3-e5dfd97ea8c8.jpeg)
![image](https://user-images.githubusercontent.com/843553/41256729-5b4c4a08-6dc2-11e8-8c17-6ec5720b6371.jpeg)

**Comment by Nastras** [comment]
Just as you describe it, I did it yesterday with me before I opened the issue. But I have no experience how well it works in the future because the time change is not the same spring or autumn beginning.

The idea behind my issue was to make the setting even more accurate, if it is not too much for you and is technically possible.

Greeting Nastras
