### ISSUE TITLE
Install and Loading Error

### ISSUE THREAD

**Issue by kevmase** [paolotremadio/homebridge-automation-calendar#3]
Hi,

I had an error when installing saying it couldn't locate the Bindings, after removing the accessory form the config.JSON I am getting this on loading Homebridge.

Can you tell me either how to fix the install problem or how to remove the plugin fully? I am a noob at this.

Running Node Version: v8.11.3
Running Homebridge Version: 0.4.43

Below is the error I get when loading Homebridge.

```
ERROR LOADING PLUGIN homebridge-automation-calendar:
[2018-6-21 20:16:09] Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/build/ed25519.node
 → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/build/Debug/ed25519.node
 → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/build/Release/ed25519.node
 → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/out/Debug/ed25519.node
 → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/Debug/ed25519.node
 → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/out/Release/ed25519.node
 → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/Release/ed25519.node
 → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/build/default/ed25519.node
 → /usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/compiled/8.11.3/linux/arm/ed25519.node
    at bindings (/usr/lib/node_modules/homebridge-automation-calendar/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-automation-calendar/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-automation-calendar/node_modules/hap-nodejs/lib/HAPServer.js:8:15)
[2018-6-21 20:16:09] ====================
```

**Comment by kevmase** [comment]
Hi,

When you say in the homebridge folder what do you mean? Mine is installed in the root within .homebridge so I am guessing I just need to run the command at the command prompt?

Thanks


Sent from my iPhone

On 21 Jun 2018, at 22:04, Paolo Tremadio <notifications@github.com<mailto:notifications@github.com>> wrote:


So, to install, this is what I would do, in the homebridge folder
rm -rf node_modules; npm install

If that doesn't work, you can remove it by doing:
npm uninstall homebridge-automation-calendar

Let me know if it works :)

**Comment by paolotremadio** [comment]
Try `npm -g uninstall homebridge-automation-calendar; npm -g install homebridge-automation-calendar`

**Comment by fabiofare** [comment]
Hello,
these are the errors during installation process:
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-automation-calendar/node_modules/curve25519-n/build'
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-automation-calendar/node_modules/curve25519-n
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

please note that I ran the installation command as following:
sudo npm -g install homebridge-automation-calendar

Thanks for support.
