### ISSUE TITLE
Does not work in automation

### ISSUE THREAD

**Issue by ahartman** [paolotremadio/homebridge-automation-calendar#5]
This is an interesting module that I would like to use. Unfortunately, it does not work.
I use the Home app from Matthias Hochgatterer to set more complex automation rules than the Apple Home app allows.
As soon as I use this plugin to set a condition in a rule, that rule will never trigger.
Even a simple "month equals 10" - in October - does not work.

I hope someone reads this and can help to get this to work.
Regards, ahartman, belgium

**Comment by paolotremadio** [comment]
Hi, I use this module in my automations and it works perfectly. It sounds like you’re doing good he right thing. Do you mind taking a screenshot of one of the automations that don’t work? 
Thanks!

**Comment by ahartman** [comment]
Paolo,

Thank you for your quick reaction. I may have solved the issue already.
I am using an older iPad - IOS 10.3.4 - as Home hub.
There were no warnings or errors when defining the automation with your plugin. They just did not work.

As test, I swapped my iPad with another one running the current IOS 13.
The automations with your plugin now run OK!

So, although there are no warnings whatsoever, IOS 10 is apparently too old for some Home stuff. I will do some more testing in the coming days and will keep you informed.


Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895

**Comment by paolotremadio** [comment]
Yes, iOS 10 is not supported anymore. Not sure if iOS 11 still works. It is difficult to remember what capabilities were supported back then. I would suggest always using latest on the one before latest. 

I close the issue for now but feel free to re-open it if you have any questions. I would be more than happy to add more values to the plugin. Let me know how you’re using it in your automation :)

**Comment by ahartman** [comment]
Paolo,

For now I am happy with your plugin.
I use in combination with homebridge-calendar.

We have a medical cabinet; the interior lighting (IKEA Tradfri) and the street light are controlled with Homekit/Homebridge.

With Applescript I generate daily event in a special calendar, starting 30 minutes before the first appointment and ending 60 minutes after the last one. 

Homebridge-calendar picks up that event exposing it in Homekit as a sensor ‘Agenda’ with contact open or closed.
From your plugin - called ‘Daylight’ - I pick up 'before sunrise’/‘daylight'/'after sunrise'.

For now I defined 6 automations.
The first three have Agenda as event and Daylight as condition.
The last two have Daylight as event and Agenda as condition:
1. Agenda - first appointment - starts before sunrise. 
Street lamp on, cabinet lights on (warm)
2. Agenda starts after sunrise and before sunset
Cabinet lights on (bright)
3. Agenda starts after sunset
Street lamp on, cabinet lights on (warm)

4. End of sunrise (time of day changes to 3)  during appointments.
Switch off street lights, cabinet lights to bright.
5. End of daylight (time of day changes to 4)  during appointments.
Switch on street lamp, switch cabinet lights to warm.

6. End of agenda
Switch off street lamp, switch off cabinet lights.

I will keep you informed on testing results.


Met vriendelijke groeten, Kind regards, Meilleures salutations,
André Hartman

**Comment by ahartman** [comment]
Paolo,

Your plugin works perfectly now that I use an IOS11 hub.

I have one wish and I do not know it this is possible in Homekit.
I would like that for one property of the plugin, to select in config.json, the actual value is displayed in the Home app icon.


Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by ahartman** [comment]
Paolo,

And one other wish.
Like with many plugins a debug setting in config.json, so that the plugin sends info to the console.
That would make setting up automations much simpler.

Met vriendelijke groeten, Kind regards, Meilleures salutations,
André Hartman

**Comment by ahartman** [comment]
I am more than happy now with the plugin. Maybe you should mention somewhere in readme.mD to use at least IOS 11 on the Homekit hub.

**Comment by ahartman** [comment]
Dear Paolo,

We communicated some time ago about your plugin.
I wonder if you can offer some help.

The plugin behaves correctly but I have problems with automation based on it.
When used as a condition everything is OK.

However, automations that use your plugin as a trigger do not fire.
I made one that should go at daylight; so when ’time of the day’ of your plugin changes from 2 to 3.
I defined that in the Home+ 4 app of Matthias Hochgatterer, since you cannot do this in the Apple Home app.

Problem is that it does not react to the change in time of the day.
I put in some test code in your index.js to fake that change from sunrise to daylight.
I see the change in the HomeBridge log but the automation does not run.

This is not an issue in your plugin but I hope you have some experience you can share to help to get this going



Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895
